# Generated by Django 5.1.2 on 2024-10-31 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_city'),
        ('routes', '0003_alter_route_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_routes', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='route',
            name='pace',
            field=models.CharField(help_text="Average pace (e.g., '5:30 min/km')", max_length=50),
        ),
    ]
