# Generated by Django 5.1.2 on 2024-10-31 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_city'),
        ('routes', '0004_alter_route_creator_alter_route_pace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
