# Generated by Django 5.1.2 on 2024-10-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
